//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinhMat_Client.ServiceReference_khachHang {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_khachHang.IService_KhachHang")]
    public interface IService_KhachHang {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/DGV_KH", ReplyAction="http://tempuri.org/IService_KhachHang/DGV_KHResponse")]
        System.Data.DataTable DGV_KH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/DGV_KH", ReplyAction="http://tempuri.org/IService_KhachHang/DGV_KHResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> DGV_KHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/insert", ReplyAction="http://tempuri.org/IService_KhachHang/insertResponse")]
        bool insert(string tenkh, int sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/insert", ReplyAction="http://tempuri.org/IService_KhachHang/insertResponse")]
        System.Threading.Tasks.Task<bool> insertAsync(string tenkh, int sdt, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/delete_KH", ReplyAction="http://tempuri.org/IService_KhachHang/delete_KHResponse")]
        bool delete_KH(int idkh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/delete_KH", ReplyAction="http://tempuri.org/IService_KhachHang/delete_KHResponse")]
        System.Threading.Tasks.Task<bool> delete_KHAsync(int idkh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/get_idKH", ReplyAction="http://tempuri.org/IService_KhachHang/get_idKHResponse")]
        int get_idKH(string tenkh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/get_idKH", ReplyAction="http://tempuri.org/IService_KhachHang/get_idKHResponse")]
        System.Threading.Tasks.Task<int> get_idKHAsync(string tenkh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/search_KH", ReplyAction="http://tempuri.org/IService_KhachHang/search_KHResponse")]
        System.Data.DataTable search_KH(string keyKH);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_KhachHang/search_KH", ReplyAction="http://tempuri.org/IService_KhachHang/search_KHResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> search_KHAsync(string keyKH);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_KhachHangChannel : KinhMat_Client.ServiceReference_khachHang.IService_KhachHang, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_KhachHangClient : System.ServiceModel.ClientBase<KinhMat_Client.ServiceReference_khachHang.IService_KhachHang>, KinhMat_Client.ServiceReference_khachHang.IService_KhachHang {
        
        public Service_KhachHangClient() {
        }
        
        public Service_KhachHangClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_KhachHangClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_KhachHangClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_KhachHangClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable DGV_KH() {
            return base.Channel.DGV_KH();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DGV_KHAsync() {
            return base.Channel.DGV_KHAsync();
        }
        
        public bool insert(string tenkh, int sdt, string diachi) {
            return base.Channel.insert(tenkh, sdt, diachi);
        }
        
        public System.Threading.Tasks.Task<bool> insertAsync(string tenkh, int sdt, string diachi) {
            return base.Channel.insertAsync(tenkh, sdt, diachi);
        }
        
        public bool delete_KH(int idkh) {
            return base.Channel.delete_KH(idkh);
        }
        
        public System.Threading.Tasks.Task<bool> delete_KHAsync(int idkh) {
            return base.Channel.delete_KHAsync(idkh);
        }
        
        public int get_idKH(string tenkh) {
            return base.Channel.get_idKH(tenkh);
        }
        
        public System.Threading.Tasks.Task<int> get_idKHAsync(string tenkh) {
            return base.Channel.get_idKHAsync(tenkh);
        }
        
        public System.Data.DataTable search_KH(string keyKH) {
            return base.Channel.search_KH(keyKH);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> search_KHAsync(string keyKH) {
            return base.Channel.search_KHAsync(keyKH);
        }
    }
}
