//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinhMat_Client.ServiceReference_loaiHang {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_loaiHang.IService_loaihang")]
    public interface IService_loaihang {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/Insert_LoaiHang", ReplyAction="http://tempuri.org/IService_loaihang/Insert_LoaiHangResponse")]
        bool Insert_LoaiHang(string maloai, string tenloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/Insert_LoaiHang", ReplyAction="http://tempuri.org/IService_loaihang/Insert_LoaiHangResponse")]
        System.Threading.Tasks.Task<bool> Insert_LoaiHangAsync(string maloai, string tenloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/editLoaiHang", ReplyAction="http://tempuri.org/IService_loaihang/editLoaiHangResponse")]
        bool editLoaiHang(string maloai, string tenloai, string maL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/editLoaiHang", ReplyAction="http://tempuri.org/IService_loaihang/editLoaiHangResponse")]
        System.Threading.Tasks.Task<bool> editLoaiHangAsync(string maloai, string tenloai, string maL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/delLoaiHang", ReplyAction="http://tempuri.org/IService_loaihang/delLoaiHangResponse")]
        bool delLoaiHang(string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/delLoaiHang", ReplyAction="http://tempuri.org/IService_loaihang/delLoaiHangResponse")]
        System.Threading.Tasks.Task<bool> delLoaiHangAsync(string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/DGV_LoaiHang", ReplyAction="http://tempuri.org/IService_loaihang/DGV_LoaiHangResponse")]
        System.Data.DataTable DGV_LoaiHang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/DGV_LoaiHang", ReplyAction="http://tempuri.org/IService_loaihang/DGV_LoaiHangResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> DGV_LoaiHangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/Search_loaiHang", ReplyAction="http://tempuri.org/IService_loaihang/Search_loaiHangResponse")]
        System.Data.DataTable Search_loaiHang(string keyloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/Search_loaiHang", ReplyAction="http://tempuri.org/IService_loaihang/Search_loaiHangResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Search_loaiHangAsync(string keyloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/get_loaiHang", ReplyAction="http://tempuri.org/IService_loaihang/get_loaiHangResponse")]
        System.Data.DataTable get_loaiHang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/get_loaiHang", ReplyAction="http://tempuri.org/IService_loaihang/get_loaiHangResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> get_loaiHangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/get_maLoai", ReplyAction="http://tempuri.org/IService_loaihang/get_maLoaiResponse")]
        string get_maLoai(string tenloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/get_maLoai", ReplyAction="http://tempuri.org/IService_loaihang/get_maLoaiResponse")]
        System.Threading.Tasks.Task<string> get_maLoaiAsync(string tenloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/get_tenLoai", ReplyAction="http://tempuri.org/IService_loaihang/get_tenLoaiResponse")]
        string get_tenLoai(string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/get_tenLoai", ReplyAction="http://tempuri.org/IService_loaihang/get_tenLoaiResponse")]
        System.Threading.Tasks.Task<string> get_tenLoaiAsync(string maloai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/tenloai", ReplyAction="http://tempuri.org/IService_loaihang/tenloaiResponse")]
        System.Data.DataTable tenloai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_loaihang/tenloai", ReplyAction="http://tempuri.org/IService_loaihang/tenloaiResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> tenloaiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_loaihangChannel : KinhMat_Client.ServiceReference_loaiHang.IService_loaihang, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_loaihangClient : System.ServiceModel.ClientBase<KinhMat_Client.ServiceReference_loaiHang.IService_loaihang>, KinhMat_Client.ServiceReference_loaiHang.IService_loaihang {
        
        public Service_loaihangClient() {
        }
        
        public Service_loaihangClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_loaihangClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_loaihangClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_loaihangClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Insert_LoaiHang(string maloai, string tenloai) {
            return base.Channel.Insert_LoaiHang(maloai, tenloai);
        }
        
        public System.Threading.Tasks.Task<bool> Insert_LoaiHangAsync(string maloai, string tenloai) {
            return base.Channel.Insert_LoaiHangAsync(maloai, tenloai);
        }
        
        public bool editLoaiHang(string maloai, string tenloai, string maL) {
            return base.Channel.editLoaiHang(maloai, tenloai, maL);
        }
        
        public System.Threading.Tasks.Task<bool> editLoaiHangAsync(string maloai, string tenloai, string maL) {
            return base.Channel.editLoaiHangAsync(maloai, tenloai, maL);
        }
        
        public bool delLoaiHang(string maloai) {
            return base.Channel.delLoaiHang(maloai);
        }
        
        public System.Threading.Tasks.Task<bool> delLoaiHangAsync(string maloai) {
            return base.Channel.delLoaiHangAsync(maloai);
        }
        
        public System.Data.DataTable DGV_LoaiHang() {
            return base.Channel.DGV_LoaiHang();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DGV_LoaiHangAsync() {
            return base.Channel.DGV_LoaiHangAsync();
        }
        
        public System.Data.DataTable Search_loaiHang(string keyloai) {
            return base.Channel.Search_loaiHang(keyloai);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Search_loaiHangAsync(string keyloai) {
            return base.Channel.Search_loaiHangAsync(keyloai);
        }
        
        public System.Data.DataTable get_loaiHang() {
            return base.Channel.get_loaiHang();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> get_loaiHangAsync() {
            return base.Channel.get_loaiHangAsync();
        }
        
        public string get_maLoai(string tenloai) {
            return base.Channel.get_maLoai(tenloai);
        }
        
        public System.Threading.Tasks.Task<string> get_maLoaiAsync(string tenloai) {
            return base.Channel.get_maLoaiAsync(tenloai);
        }
        
        public string get_tenLoai(string maloai) {
            return base.Channel.get_tenLoai(maloai);
        }
        
        public System.Threading.Tasks.Task<string> get_tenLoaiAsync(string maloai) {
            return base.Channel.get_tenLoaiAsync(maloai);
        }
        
        public System.Data.DataTable tenloai() {
            return base.Channel.tenloai();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> tenloaiAsync() {
            return base.Channel.tenloaiAsync();
        }
    }
}
