//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinhMat_Client.ServiceReference_chiTietHD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_chiTietHD.IService_ChiTietHoaDon")]
    public interface IService_ChiTietHoaDon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_ChiTietHoaDon/insert_CTHD", ReplyAction="http://tempuri.org/IService_ChiTietHoaDon/insert_CTHDResponse")]
        bool insert_CTHD(int idhd, int idsp, int soluong, int thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_ChiTietHoaDon/insert_CTHD", ReplyAction="http://tempuri.org/IService_ChiTietHoaDon/insert_CTHDResponse")]
        System.Threading.Tasks.Task<bool> insert_CTHDAsync(int idhd, int idsp, int soluong, int thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_ChiTietHoaDon/DGV_CTHD", ReplyAction="http://tempuri.org/IService_ChiTietHoaDon/DGV_CTHDResponse")]
        System.Data.DataTable DGV_CTHD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_ChiTietHoaDon/DGV_CTHD", ReplyAction="http://tempuri.org/IService_ChiTietHoaDon/DGV_CTHDResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> DGV_CTHDAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_ChiTietHoaDonChannel : KinhMat_Client.ServiceReference_chiTietHD.IService_ChiTietHoaDon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_ChiTietHoaDonClient : System.ServiceModel.ClientBase<KinhMat_Client.ServiceReference_chiTietHD.IService_ChiTietHoaDon>, KinhMat_Client.ServiceReference_chiTietHD.IService_ChiTietHoaDon {
        
        public Service_ChiTietHoaDonClient() {
        }
        
        public Service_ChiTietHoaDonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_ChiTietHoaDonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ChiTietHoaDonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_ChiTietHoaDonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool insert_CTHD(int idhd, int idsp, int soluong, int thanhtien) {
            return base.Channel.insert_CTHD(idhd, idsp, soluong, thanhtien);
        }
        
        public System.Threading.Tasks.Task<bool> insert_CTHDAsync(int idhd, int idsp, int soluong, int thanhtien) {
            return base.Channel.insert_CTHDAsync(idhd, idsp, soluong, thanhtien);
        }
        
        public System.Data.DataTable DGV_CTHD() {
            return base.Channel.DGV_CTHD();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DGV_CTHDAsync() {
            return base.Channel.DGV_CTHDAsync();
        }
    }
}
