//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinhMat_Client.ServiceReference_xuatKho {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_xuatKho.IService_XuatKho")]
    public interface IService_XuatKho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/DGV_xuatKho", ReplyAction="http://tempuri.org/IService_XuatKho/DGV_xuatKhoResponse")]
        System.Data.DataTable DGV_xuatKho();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/DGV_xuatKho", ReplyAction="http://tempuri.org/IService_XuatKho/DGV_xuatKhoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> DGV_xuatKhoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/insert_xuatKho", ReplyAction="http://tempuri.org/IService_XuatKho/insert_xuatKhoResponse")]
        bool insert_xuatKho(int idsp, int sl, int thanhtien, System.DateTime ngay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/insert_xuatKho", ReplyAction="http://tempuri.org/IService_XuatKho/insert_xuatKhoResponse")]
        System.Threading.Tasks.Task<bool> insert_xuatKhoAsync(int idsp, int sl, int thanhtien, System.DateTime ngay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/check_IDXuat", ReplyAction="http://tempuri.org/IService_XuatKho/check_IDXuatResponse")]
        bool check_IDXuat(int idsp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/check_IDXuat", ReplyAction="http://tempuri.org/IService_XuatKho/check_IDXuatResponse")]
        System.Threading.Tasks.Task<bool> check_IDXuatAsync(int idsp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/get_soLuongXuat", ReplyAction="http://tempuri.org/IService_XuatKho/get_soLuongXuatResponse")]
        int get_soLuongXuat(int idsp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/get_soLuongXuat", ReplyAction="http://tempuri.org/IService_XuatKho/get_soLuongXuatResponse")]
        System.Threading.Tasks.Task<int> get_soLuongXuatAsync(int idsp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/update_SLXuat", ReplyAction="http://tempuri.org/IService_XuatKho/update_SLXuatResponse")]
        bool update_SLXuat(int idsp, int sl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/update_SLXuat", ReplyAction="http://tempuri.org/IService_XuatKho/update_SLXuatResponse")]
        System.Threading.Tasks.Task<bool> update_SLXuatAsync(int idsp, int sl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/get_tongTienXuat", ReplyAction="http://tempuri.org/IService_XuatKho/get_tongTienXuatResponse")]
        int get_tongTienXuat(int idsp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/get_tongTienXuat", ReplyAction="http://tempuri.org/IService_XuatKho/get_tongTienXuatResponse")]
        System.Threading.Tasks.Task<int> get_tongTienXuatAsync(int idsp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/update_tongTienXuat", ReplyAction="http://tempuri.org/IService_XuatKho/update_tongTienXuatResponse")]
        bool update_tongTienXuat(int idsp, int thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/update_tongTienXuat", ReplyAction="http://tempuri.org/IService_XuatKho/update_tongTienXuatResponse")]
        System.Threading.Tasks.Task<bool> update_tongTienXuatAsync(int idsp, int thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/search_loaiXk", ReplyAction="http://tempuri.org/IService_XuatKho/search_loaiXkResponse")]
        System.Data.DataTable search_loaiXk(string loaisp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/search_loaiXk", ReplyAction="http://tempuri.org/IService_XuatKho/search_loaiXkResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> search_loaiXkAsync(string loaisp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/search_dateXK", ReplyAction="http://tempuri.org/IService_XuatKho/search_dateXKResponse")]
        System.Data.DataTable search_dateXK(System.DateTime fromdate, System.DateTime enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/search_dateXK", ReplyAction="http://tempuri.org/IService_XuatKho/search_dateXKResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> search_dateXKAsync(System.DateTime fromdate, System.DateTime enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/search_nameXK", ReplyAction="http://tempuri.org/IService_XuatKho/search_nameXKResponse")]
        System.Data.DataTable search_nameXK(string tensp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_XuatKho/search_nameXK", ReplyAction="http://tempuri.org/IService_XuatKho/search_nameXKResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> search_nameXKAsync(string tensp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_XuatKhoChannel : KinhMat_Client.ServiceReference_xuatKho.IService_XuatKho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_XuatKhoClient : System.ServiceModel.ClientBase<KinhMat_Client.ServiceReference_xuatKho.IService_XuatKho>, KinhMat_Client.ServiceReference_xuatKho.IService_XuatKho {
        
        public Service_XuatKhoClient() {
        }
        
        public Service_XuatKhoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_XuatKhoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_XuatKhoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_XuatKhoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable DGV_xuatKho() {
            return base.Channel.DGV_xuatKho();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DGV_xuatKhoAsync() {
            return base.Channel.DGV_xuatKhoAsync();
        }
        
        public bool insert_xuatKho(int idsp, int sl, int thanhtien, System.DateTime ngay) {
            return base.Channel.insert_xuatKho(idsp, sl, thanhtien, ngay);
        }
        
        public System.Threading.Tasks.Task<bool> insert_xuatKhoAsync(int idsp, int sl, int thanhtien, System.DateTime ngay) {
            return base.Channel.insert_xuatKhoAsync(idsp, sl, thanhtien, ngay);
        }
        
        public bool check_IDXuat(int idsp) {
            return base.Channel.check_IDXuat(idsp);
        }
        
        public System.Threading.Tasks.Task<bool> check_IDXuatAsync(int idsp) {
            return base.Channel.check_IDXuatAsync(idsp);
        }
        
        public int get_soLuongXuat(int idsp) {
            return base.Channel.get_soLuongXuat(idsp);
        }
        
        public System.Threading.Tasks.Task<int> get_soLuongXuatAsync(int idsp) {
            return base.Channel.get_soLuongXuatAsync(idsp);
        }
        
        public bool update_SLXuat(int idsp, int sl) {
            return base.Channel.update_SLXuat(idsp, sl);
        }
        
        public System.Threading.Tasks.Task<bool> update_SLXuatAsync(int idsp, int sl) {
            return base.Channel.update_SLXuatAsync(idsp, sl);
        }
        
        public int get_tongTienXuat(int idsp) {
            return base.Channel.get_tongTienXuat(idsp);
        }
        
        public System.Threading.Tasks.Task<int> get_tongTienXuatAsync(int idsp) {
            return base.Channel.get_tongTienXuatAsync(idsp);
        }
        
        public bool update_tongTienXuat(int idsp, int thanhtien) {
            return base.Channel.update_tongTienXuat(idsp, thanhtien);
        }
        
        public System.Threading.Tasks.Task<bool> update_tongTienXuatAsync(int idsp, int thanhtien) {
            return base.Channel.update_tongTienXuatAsync(idsp, thanhtien);
        }
        
        public System.Data.DataTable search_loaiXk(string loaisp) {
            return base.Channel.search_loaiXk(loaisp);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> search_loaiXkAsync(string loaisp) {
            return base.Channel.search_loaiXkAsync(loaisp);
        }
        
        public System.Data.DataTable search_dateXK(System.DateTime fromdate, System.DateTime enddate) {
            return base.Channel.search_dateXK(fromdate, enddate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> search_dateXKAsync(System.DateTime fromdate, System.DateTime enddate) {
            return base.Channel.search_dateXKAsync(fromdate, enddate);
        }
        
        public System.Data.DataTable search_nameXK(string tensp) {
            return base.Channel.search_nameXK(tensp);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> search_nameXKAsync(string tensp) {
            return base.Channel.search_nameXKAsync(tensp);
        }
    }
}
